const $=id=>document.getElementById(id);
const db={sales:JSON.parse(localStorage.getItem('sales')||'[]'),contracts:JSON.parse(localStorage.getItem('contracts')||'[]'),quotes:JSON.parse(localStorage.getItem('quotes')||'[]'),reports:JSON.parse(localStorage.getItem('reports')||'[]'),payments:JSON.parse(localStorage.getItem('payments')||'[]'),users:JSON.parse(localStorage.getItem('users')||'[]')};
function save(){Object.keys(db).forEach(k=>localStorage.setItem(k,JSON.stringify(db[k])));render();}
function seed(){if(!db.sales.length){db.sales=[{client:'عميل ABC',phone:'0500000000',service:'عقد صيانة سلامة',value:12000,status:'طلب عرض سعر جديد',follow:'اليوم'},{client:'عميل XYZ',phone:'0550000000',service:'صيانة طارئة',value:3200,status:'تم إرسال عرض السعر',follow:'تذكير بعد 3 أيام'}];db.contracts=[{client:'فندق تجريبي',start:'2026-05-01',end:'2027-05-01',value:120000,visits:12,status:'نشط'},{client:'مجمع تجاري',start:'2026-05-01',end:'2026-05-20',value:80000,visits:4,status:'ينتهي قريباً'}];db.quotes=[{client:'عميل ABC',type:'صيانة مضخة حريق',value:4500,status:'تم تحرير عرض سعر',reminder:'كل 3 أيام'},{client:'عميل XYZ',type:'استبدال كواشف',value:6200,status:'تم التعميد',reminder:'تم عمل الصيانة'}];db.reports=[{client:'فندق تجريبي',engineer:'المهندس أحمد',date:'2026-05-08',excel:'Excel Sheet',pdf:'PDF Report',notes:'تم رفع التقرير'}];db.payments=[{client:'فندق تجريبي',payment:'الأولى',amount:25000,status:'تم الاستلام',due:'2026-05-10'},{client:'فندق تجريبي',payment:'الثانية',amount:25000,status:'لم يتم السداد',due:'2026-11-10'}];db.users=[{name:'المدير العام',role:'مدير',permissions:'كل الصلاحيات',status:'نشط'},{name:'مهندس صيانة',role:'مهندس',permissions:'العقود والتقارير',status:'نشط'},{name:'فني',role:'فني',permissions:'المهام والتقارير',status:'نشط'},{name:'محاسب',role:'محاسب',permissions:'المحاسبة والدفعات',status:'نشط'}];save();}}
function money(n){return Number(n||0).toLocaleString('ar-SA')+' ر.س'}
function expiring(){return db.contracts.filter(c=>{let d=Math.ceil((new Date(c.end)-new Date())/86400000);return d>=0&&d<=15}).length}
function setPage(id){document.querySelectorAll('.page').forEach(p=>p.classList.remove('active'));document.querySelectorAll('.side-link').forEach(b=>b.classList.remove('active'));$(id).classList.add('active');document.querySelector(`[data-target="${id}"]`)?.classList.add('active');}
document.querySelectorAll('.side-link').forEach(b=>b.onclick=()=>setPage(b.dataset.target));document.querySelectorAll('[data-open]').forEach(x=>x.onclick=()=>setPage(x.dataset.open));
function table(id,arr,fn){$(id).innerHTML=arr.map(fn).join('')}
function render(){$('newQuotation').textContent=db.sales.filter(x=>x.status==='طلب عرض سعر جديد').length||24;$('inProgress').textContent=db.sales.filter(x=>x.status==='تحت التنفيذ').length||16;$('quotationSent').textContent=db.sales.filter(x=>x.status==='تم إرسال عرض السعر').length||12;$('salesAwarded').textContent=db.sales.filter(x=>x.status.includes('تعميد')||x.status.includes('أرشيف')).length||8;$('totalContracts').textContent=db.contracts.length||128;$('contractsCount').textContent=db.contracts.length||128;$('totalValue').textContent=money(db.contracts.reduce((a,b)=>a+Number(b.value||0),0)||1250000);$('expiringContracts').textContent=expiring()||7;$('quotePrepared').textContent=db.quotes.filter(x=>x.status==='تم تحرير عرض سعر').length||36;$('awardedArchived').textContent=db.quotes.filter(x=>x.status.includes('تعميد')||x.status.includes('أرشيف')).length||22;$('maintenanceDone').textContent=db.quotes.filter(x=>x.status==='تم عمل الصيانة').length||15;table('salesTable',db.sales,(x,i)=>`<tr><td>${x.client}</td><td>${x.phone}</td><td>${x.service}</td><td>${money(x.value)}</td><td><select onchange="db.sales[${i}].status=this.value;save()">${['طلب عرض سعر جديد','تحت التنفيذ','تم إرسال عرض السعر','تم التعميد','لم يتم التعميد - أرشيف'].map(s=>`<option ${x.status===s?'selected':''}>${s}</option>`).join('')}</select></td><td>${x.follow}</td></tr>`);table('contractsTable',db.contracts,x=>`<tr><td>${x.client}</td><td>${x.start}</td><td>${x.end}</td><td>${money(x.value)}</td><td>${x.visits}</td><td>${x.status}</td></tr>`);table('quotesTable',db.quotes,(x,i)=>`<tr><td>${x.client}</td><td>${x.type}</td><td>${money(x.value)}</td><td><select onchange="db.quotes[${i}].status=this.value;save()">${['تم تحرير عرض سعر','تم التعميد','لم يتم التعميد - الأرشيف','تم عمل الصيانة'].map(s=>`<option ${x.status===s?'selected':''}>${s}</option>`).join('')}</select></td><td>${x.reminder}</td><td>فتح</td></tr>`);table('reportsTable',db.reports,x=>`<tr><td>${x.client}</td><td>${x.engineer}</td><td>${x.date}</td><td>${x.excel}</td><td>${x.pdf}</td><td>${x.notes}</td></tr>`);table('paymentsTable',db.payments,x=>`<tr><td>${x.client}</td><td>${x.payment}</td><td>${money(x.amount)}</td><td>${x.status}</td><td>${x.due}</td></tr>`);table('usersTable',db.users,x=>`<tr><td>${x.name}</td><td>${x.role}</td><td>${x.permissions}</td><td>${x.status}</td></tr>`);}
function tick(){let now=new Date();$('time').textContent=now.toLocaleTimeString('en-US');$('date').textContent=now.toLocaleDateString('ar-SA',{weekday:'long',year:'numeric',month:'long',day:'numeric'})+' | '+now.toLocaleDateString('en-US',{weekday:'long',year:'numeric',month:'long',day:'numeric'});}
setInterval(tick,1000);tick();
function openModal(title,fields,onSave){$('modalTitle').textContent=title;$('modalFields').innerHTML=fields.map(f=>`<div class="field"><label>${f[1]}</label><input name="${f[0]}" type="${f[2]||'text'}" required></div>`).join('');$('modal').showModal();$('saveModal').onclick=e=>{e.preventDefault();onSave(Object.fromEntries(new FormData($('modalForm')).entries()));$('modalForm').reset();$('modal').close();save();};}
$('addSalesBtn').onclick=()=>openModal('إضافة عميل مبيعات',[['client','العميل'],['phone','الجوال'],['service','الخدمة'],['value','القيمة'],['follow','آخر متابعة']],d=>{d.status='طلب عرض سعر جديد';db.sales.push(d)});
$('addContractBtn').onclick=()=>openModal('إضافة عقد',[['client','العميل'],['start','البداية','date'],['end','النهاية','date'],['value','القيمة'],['visits','عدد الزيارات']],d=>{d.status='نشط';db.contracts.push(d)});
$('addQuoteBtn').onclick=()=>openModal('إضافة عرض صيانة',[['client','العميل'],['type','نوع الصيانة'],['value','القيمة'],['reminder','التذكير']],d=>{d.status='تم تحرير عرض سعر';db.quotes.push(d)});
$('addReportBtn').onclick=()=>openModal('إضافة تقرير فني',[['client','العميل'],['engineer','المهندس/الفني'],['date','التاريخ','date'],['excel','رابط Excel'],['pdf','رابط PDF'],['notes','ملاحظات']],d=>db.reports.push(d));
$('addPaymentBtn').onclick=()=>openModal('إضافة دفعة',[['client','العميل'],['payment','رقم الدفعة'],['amount','قيمة الدفعة'],['status','الحالة'],['due','تاريخ الاستحقاق','date']],d=>db.payments.push(d));
$('addUserBtn').onclick=()=>openModal('إضافة مستخدم',[['name','الاسم'],['role','الدور'],['permissions','الصلاحيات'],['status','الحالة']],d=>db.users.push(d));
seed();render();
